import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const DEBUG_BLOCK_START = "/*  *** DEBUG START ***";
export const DEBUG_BLOCK_END = "//  *** DEBUG END ***/";
const DEBUG_BLOCK_PATTERN = /\/\*\s+\*\*\* DEBUG START \*\*\*[\s\S]*?\/\/\s+\*\*\* DEBUG END \*\*\*\//g;
const NODE_TEST_BANNER = "Remove comments for testing in NODE";

/** @type {readonly string[]} */
export const SOURCE_FILES = Object.freeze([
    "CacheFinance.js",
    "ScriptSettings.js",
    "CacheFinance3rdParty.js",
    "CacheFinanceTest.js",
    "CacheFinanceWebSites.js",
    "CacheFinanceUtils.js"
]);

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const paths = Object.freeze({
    root: rootDir,
    src: path.join(rootDir, "src"),
    dist: path.join(rootDir, "dist", "CacheFinance.js")
});

/**
 * Remove Node.js-only DEBUG blocks from Apps Script source files.
 * @param {string} content
 * @returns {string}
 */
export function stripDebugBlocks(content) {
    return content.replace(DEBUG_BLOCK_PATTERN, "").trim();
}

/**
 * Uncomment DEBUG blocks so Vitest can import src modules in Node.
 * @param {string} content
 * @returns {string}
 */
export function enableDebugExports(content) {
    if (!content.includes(DEBUG_BLOCK_START)) {
        return content;
    }

    const startIdx = content.indexOf(DEBUG_BLOCK_START);
    const endIdx = content.indexOf(DEBUG_BLOCK_END, startIdx);
    if (endIdx === -1) {
        return content;
    }

    const before = content.slice(0, startIdx);
    const after = content.slice(endIdx + DEBUG_BLOCK_END.length);
    const debugBody = content.slice(startIdx + DEBUG_BLOCK_START.length, endIdx);

    const uncommented = debugBody
        .split("\n")
        .map((line) => line.replace(/^\/\/\s?/, ""))
        .filter((line) => line.trim() !== NODE_TEST_BANNER)
        .join("\n");

    return `${before}${uncommented}${after}`;
}

/**
 * @param {string[]} sections
 * @returns {string}
 */
export function hashSections(sections) {
    return crypto
        .createHash("sha256")
        .update(sections.join("\0"))
        .digest("hex")
        .slice(0, 12);
}

/**
 * @param {string} sourceHash
 * @returns {string}
 */
export function createBundleBanner(sourceHash) {
    return [
        "/*",
        " * CacheFinance Apps Script bundle.",
        " * Generated from src/. Do not edit this file directly.",
        ` * Source hash: ${sourceHash}`,
        " */",
        ""
    ].join("\n");
}

/**
 * @param {string} content
 */
export function validateBundleContent(content) {
    const errors = [];

    if (!content.includes("function CACHEFINANCE")) {
        errors.push("missing CACHEFINANCE custom function");
    }
    if (!content.includes("function CACHEFINANCES")) {
        errors.push("missing CACHEFINANCES custom function");
    }
    if (content.includes("DEBUG START")) {
        errors.push("contains DEBUG block markers");
    }
    if (content.includes("GasMocks")) {
        errors.push("contains test-only GasMocks references");
    }
    if (/^\s*import\s+/m.test(content) || /^\s*export\s+/m.test(content)) {
        errors.push("contains ES module import/export statements");
    }

    if (errors.length > 0) {
        throw new Error(`Invalid bundle: ${errors.join(", ")}`);
    }
}

/**
 * @returns {string[]}
 */
export function readSourceSections() {
    return SOURCE_FILES.map((fileName) => {
        const filePath = path.join(paths.src, fileName);
        if (!fs.existsSync(filePath)) {
            throw new Error(`Missing source file: ${filePath}`);
        }

        return stripDebugBlocks(fs.readFileSync(filePath, "utf8"));
    });
}

/**
 * @returns {{ bundle: string, sourceHash: string, sectionCount: number }}
 */
export function buildCacheFinanceBundle() {
    const sections = readSourceSections();
    const sourceHash = hashSections(sections);
    const bundle = `${createBundleBanner(sourceHash)}${sections.join("\n\n")}\n`;

    validateBundleContent(bundle);

    return {
        bundle,
        sourceHash,
        sectionCount: sections.length
    };
}

/**
 * @returns {{ written: boolean, bundle: string, sourceHash: string, bytes: number }}
 */
export function writeCacheFinanceBundle() {
    const { bundle, sourceHash, sectionCount } = buildCacheFinanceBundle();
    const bytes = Buffer.byteLength(bundle, "utf8");
    const previous = fs.existsSync(paths.dist) ? fs.readFileSync(paths.dist, "utf8") : null;

    if (previous === bundle) {
        return { written: false, bundle, sourceHash, bytes, sectionCount };
    }

    fs.mkdirSync(path.dirname(paths.dist), { recursive: true });
    fs.writeFileSync(paths.dist, bundle, "utf8");

    return { written: true, bundle, sourceHash, bytes, sectionCount };
}

/**
 * @returns {boolean}
 */
export function isCacheFinanceBundleCurrent() {
    if (!fs.existsSync(paths.dist)) {
        return false;
    }

    const { bundle } = buildCacheFinanceBundle();
    return fs.readFileSync(paths.dist, "utf8") === bundle;
}
